### ISSUE TITLE
resize fail

### ISSUE THREAD

**Issue by hyyoxhk** [STMicroelectronics/STM32MPU_EmbSW_Overall_Offer#2]
I am sorry to raise issues here, I'd like to be able to build an SD card image, deploy to a system and have it automatically resize on first boot. I built a mirror by referring to the [url](https://wiki.stmicroelectronics.cn/stm32mpu/wiki/STM32MP1_Distribution_Package) , and get a FlashLayout_sdcard_stm32mp157c-dk2-trusted.raw image by running the create_sdcard_from_flashlayout.sh script, but it can not resize when i used the dd command write to sdcard(16G)
![2021-04-29 23-09-40](https://user-images.githubusercontent.com/42868698/116581886-5fcd6300-a947-11eb-8c4d-7759b9129bca.png)

**Comment by cpriouzeau** [comment]
HI, The file system are resized correctly following the information used during the creation of raw sdcard. The tools create_sdcard_from_flashlayout.sh limit by default the size of raw to 1.5GB (DEFAULT_RAW_SIZE=1536) . To change the size you can change the DEFAULT_RAW_SIZE on script or at runtime with sgdisk you can extend the size of last partition.
